use aceso;

insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('37347680', 'BENZALKONIUM CHLORIDE', 'SAS HEALTHCARE INC', 'ZALIEX ALCOHOL-FREE ANTISEPTIC HAND SANITIZER', 9037);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('15833125', 'ENALAPRIL MALEATE', 'REMEDYREPACK INC.', 'ENALAPRIL MALEATE', 2383);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('88200006', 'IPILIMUMAB', 'E.R. SQUIBB & SONS, L.L.C.', 'YERVOY', 1058);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('86244677', 'PAROXETINE HYDROCHLORIDE', 'APOTEX CORP', 'PAXIL', 8527);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('87398843', 'BENAZEPRIL HYDROCHLORIDE AND HYDROCHLOROTHIAZIDE', 'NOVARTIS PHARMACEUTICALS CORPORATION', 'LOTENSIN HCT', 5512);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('79031267', 'DEXTROMETHORPHAN, BROMPHENIRAMINE MALEATE, PHENYLEPHRINE HYDROCHLORIDE', 'EFFICIENT LABORATORIES INC', 'ROMPE PECHO', 8705);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('03615779', 'ALUMINUM HYDROXIDE, BISMUTH SUBCARBONATE, CALCIUM CARBONATE, MAGNESIUM CARBONATE, SODIUM BICARBONATE', 'LABORATORIOS IMPERIALES, S.A. DE C.V.', 'ESTOMAROL', 2794);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('60203490', 'ACETAMINOPHEN, CHLORPHENIRAMINE MALEATE, DEXTROMETHORPHAN HBR, PHENYLEPHRINE HCL', 'RICHMOND DIVISION OF WYETH', 'CHILDRENS DIMETAPP MULTISYMPTOM COLD AND FLU', 1146);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('47500886', 'ALCOHOL', 'DAVION, INC', 'PERFECT PURITY ADVANCED HAND SANITIZER REFRESHING', 6423);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('21624216', 'ZINC OXIDE AND OCTINOXATE', 'OMP, INC.', 'NU-DERM SUN SHIELD SPF 50 SUNSCREEN', 8112);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('73196479', 'OXYGEN', 'MIDDLESEX WELDING SALES CO, INC.', 'OXYGEN', 3441);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('79010685', 'CLOBETASOL PROPIONATE', 'REBEL DISTRIBUTORS CORP', 'CLOBETASOL PROPIONATE', 9891);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('20401627', 'ETOMIDATE', 'MYLAN INSTITUTIONAL LLC', 'ETOMIDATE', 5146);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('61051517', 'IRBESARTAN', 'AMERICAN HEALTH PACKAGING', 'IRBESARTAN', 1819);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('33954478', 'AMITRIPTYLINE HYDROCHLORIDE', 'H.J. HARKINS COMPANY, INC.', 'AMITRIPTYLINE HYDROCHLORIDE', 6427);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('21730576', 'BENAZEPRIL HYDROCHLORIDE', 'MYLAN PHARMACEUTICALS INC.', 'BENAZEPRIL HYDROCHLORIDE', 7540);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('53393124', 'ADENOSINUM CYCLOPHOSPHORICUM, ADRENOCORTICOTROPHIN, ALLIUM CEPA, ARSENICUM ALBUM, CORTISONE ACETICUM, EUPHRASIA OFFICINALIS, GALPHIMIA GLAUCA, HISTAMINUM HYDROCHLORICUM, KALI MURIATICUM, MUCOSA NASALIS SUIS, NATRUM MURIATICUM, RNA, SABADILLA', 'NEW SUN INC.', 'ALLERGIES FOUNDATIONAL FORMULA', 8638);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('40641688', 'GUAIFENESIN AND DEXTROMETHORPHAN HYDROBROMIDE', 'PHYSICIANS TOTAL CARE, INC.', 'MUCINEX DM', 4425);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('59650264', 'HYDROCODONE BITARTRATE AND ACETAMINOPHEN', 'WATSON PHARMA, INC.', 'MAXIDONE', 6467);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('51486448', 'LYCOPODIUM CLAVATUM SPORE', 'NATURAL HEALTH SUPPLY', 'UPSET STOMACH, CONSTIPATION', 9191);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('28038299', 'ACTIVATED CHARCOAL - AETHUSA CYNAPIUM - APOMORPHINE HYDROCHLORIDE - BRYONIA ALBA ROOT - COLCHICUM AUTUMNALE BULB - IPECAC - LYCOPODIUM CLAVATUM SPORE - STRYCHNOS IGNATII SEED - STRYCHNOS NUX-VOMICA SE', 'GUNA SPA', 'GUNA-REFLUX', 3739);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('03186633', 'BENZETHONIUM CHLORIDE', 'FIVE BELOW', 'CANDY APPLE ANTI BACTERIAL HAND SANITIZER', 7518);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('33131261', 'OXYCODONE AND ACETAMINOPHEN', 'ROXANE LABORATORIES, INC.', 'ROXICET', 4470);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('52001441', 'DONEPEZIL HYDROCHLORIDE', 'DR. REDDYS LABORATORIES LIMITED', 'DONEPEZIL HYDROCHLORIDE', 2989);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('40983508', 'OCTINOXATE, OCTISALATE, AVOBENZONE, OCTOCRYLENE', 'LABORATOIRES CLARINS S.A.', 'CLARINS ADVANCED EXTRA-FIRMING DAY', 7829);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('44147268', 'ACCONITUM FEROX, ADRENALIUM, APIS MELLIFICA, ARGENTUM NITRICUM, AVENA SATIVA, BAPTISIA TINCTORIA, COCHLEARIA ARMORACIA, PHOSPHORUS, MEDORRHINUM, SUMBULUS MOSCHATUS, SCUTELLARIA LATERFOLIA, VIOLA ODORATA, LITSEA CUBEBA, AESCULUS HIPPOCASTANUM, MENTHA PIPERITA, SCLERANTHUS ANNUUS', 'IONX HOLDINGS D/B/A HELLOLIFE INC.', 'SYNAPTOL', 8231);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('88853565', 'VALSARTAN AND HYDROCHLOROTHIAZIDE', 'NOVARTIS PHARMACEUTICALS CORPORATION', 'DIOVAN HCT', 109);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('23784874', 'VANCOMYCIN HYDROCHLORIDE', 'MYLAN INSTITUTIONAL LLC', 'VANCOMYCIN HYDROCHLORIDE', 1641);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('15780125', 'HOMEOPATHIC GEL', 'ENERGETIX CORP', 'PHYTOGEL', 4017);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('93337000', 'LAMOTRIGINE EXTENDED RELEASE', 'PAR PHARMACEUTICAL INC.', 'LAMOTRIGINE EXTENDED RELEASE', 8357);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('30869034', 'TRICLOSAN', 'DUKAL CORPORATION', 'DAWNMIST DEODORANT', 9193);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('92266575', 'TESTOSTERONE', 'PRASCO LABORATORIES', 'TESTOSTERONE GEL', 2594);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('61310306', 'VANILLA', 'NELCO LABORATORIES, INC.', 'VANILLA', 151);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('23634351', 'TRIMETHOBENZAMIDE HYDROCHLORIDE', 'REMEDYREPACK INC.', 'TIGAN', 8126);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('62531542', 'ALCOHOL', 'HYDROX LABORATORIES', 'INSTANT HAND SANITIZER', 3609);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('98572852', 'NAPROXEN SODIUM', 'DOLGENCORP, LLC', 'DG HEALTH NAPROXEN SODIUM', 2956);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('05436604', 'CARVEDILOL', 'LAKE ERIE MEDICAL & SURGICAL SUPPLY DBA QUALITY CARE PRODUCTS LLC', 'COREG', 5239);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('27363279', 'CALCIUM CARBONATE', 'GLAXOSMITHKLINE CONSUMER HEALTHCARE LP', 'TUMS', 4310);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('62979617', 'ZINC OXIDE', 'ARBONNE INTERNATIONAL, LLC', 'PERFECTING LIQUID FOUNDATION EARTHY BEIGE', 2970);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('97368846', 'POA ANNUA POLLEN', 'ALLERGY LABORATORIES, INC.', 'ANNUAL BLUEGRASS POLLEN', 3875);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('76752124', 'CLOPIDOGREL', 'WOCKHARDT USA LLC.', 'CLOPIDOGREL', 6249);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('89241602', 'BENZALKONIUM CHLORIDE', 'BOLERO HOME DECOR, INC.', 'DISNEY PIXAR TOY STORY ANTIBACTERIAL HAND WIPES', 8104);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('89924067', 'INDOMETHACIN', 'BRYANT RANCH PREPACK', 'INDOMETHACIN', 2598);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('35292224', 'SODIUM FLUORIDE', 'AMERICAN AMENITIES, INC.', 'MEGAFRESH', 2732);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('90565111', 'ERYTHROMYCIN', 'CARILION MATERIALS MANAGEMENT', 'ERY-TAB', 9040);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('51270316', 'VERAPAMIL HYDROCHLORIDE', 'UCB, INC.', 'VERELAN PM', 7816);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('74327354', 'PYRITHIONE ZINC', 'PROCTER & GAMBLE MANUFACTURING CO.', 'HEAD AND SHOULDERS', 9377);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('89555530', 'NAPROXEN SODIUM', 'VICTORY PHARMA, INC.', 'NAPRELAN', 8197);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('29153702', 'OCTINOXATE AND OXYBEZONE', 'AUTUMN HARP, INC', 'GAP FAVORITE LIP BALM', 7625);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('87339042', 'ACETAMINOPHEN', 'TIME CAP LABS INC', 'ACETAMINOPHEN', 6568);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('54924456', 'ACETAMINOPHEN, DEXTROMETHORPHAN HBR, PHENYLEPHRINE HCL', 'SHOPKO STORES OPERATING CO., LLC', 'DAYTIME', 4076);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('14284170', 'ATENOLOL', 'AIDAREX PHARMACEUTICALS LLC', 'ATENOLOL', 6694);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('79863598', 'ATENOLOL', 'BLENHEIM PHARMACAL, INC.', 'ATENOLOL', 1841);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('22064089', 'TECHNETIUM TC-99M SODIUM PERTECHNETATE', 'MEDI-PHYSICS INC.', 'TECHNETIUM TC99M GENERATOR', 7647);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('62551757', 'OCTINOXATE, OCTISALATE, AVOBENZONE', 'ANASTASIA BEVERLY HILLS', 'FLAWLESS TINTED MOISTURIZER DARK', 275);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('20256238', 'ASIAN GINSENG', 'KOREA GINSENG CORPORATION', 'CHEONG-KWAN-JANG SLICED KOREAN HONGSAM', 5583);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('47270802', 'NABUMETONE', 'PREFERRED PHARMACEUTICALS, INC.', 'NABUMETONE', 8573);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('07139109', 'DICLOFENAC SODIUM', 'STAT RX USA', 'DICLOFENAC SODIUM', 1181);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('58935293', 'METRONIDAZOLE', 'CLARIS LIFESCIENCES INC.', 'METRONIDAZOLE', 8485);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('98416353', 'POVIDONE-IODINE', 'WALGREEN COMPANY', 'APOTHECARY PVP TOPICAL', 1451);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('55398006', 'ATORVASTATIN CALCIUM', 'LEGACY PHARMACEUTICAL PACKAGING', 'ATORVASTATIN CALCIUM', 7960);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('46536270', 'BENZALKONIUM CHLORIDE', 'CVS PHARMACY', 'ANTIBACTERIAL MOISTURIZING HAND LOTION', 8822);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('50082768', 'CIMICIFUGA, LACHESIS TRIGONOCEPHALUS, LILIUM TIGRINUM', 'NARTEX LABORATORIOS HOMEOPATICOS SA DE CV', 'MENOP-AID', 3870);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('41963341', 'PHENELZINE SULFATE', 'PARKE-DAVIS DIV OF PFIZER INC', 'NARDIL', 1532);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('90096057', 'TELMISARTAN AND HYDROCHLORTHIAZIDE', 'TORRENT PHARMACEUTICALS LIMITED', 'TELMISARTAN AND HYDROCHLORTHIAZIDE', 3558);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('17591643', 'MENTHOL, METHYL SALICYLATE', 'FABRICATION ENTERPRISES', 'COLD SPOT', 1859);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('77823370', 'RED MAPLE', 'NELCO LABORATORIES, INC.', 'RED MAPLE', 8703);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('24868189', 'ETODOLAC', 'PHYSICIANS TOTAL CARE, INC.', 'ETODOLAC', 6681);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('25627881', 'PEMETREXED DISODIUM', 'ELI LILLY AND COMPANY', 'ALIMTA', 3183);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('33958006', 'BUTALBITAL, ACETAMINOPHEN, AND CAFFEINE', 'BRYANT RANCH PREPACK', 'BUTALBITAL, ACETAMINOPHEN AND CAFFEINE', 366);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('06116786', 'GLYCOPYRROLATE', 'AMERICAN HEALTH PACKAGING', 'GLYCOPYRROLATE', 3112);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('58383958', 'PRIVET', 'ANTIGEN LABORATORIES, INC.', 'PRIVET', 7128);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('69965754', 'IBUPROFEN', 'MAJOR PHARMACEUTICALS', 'IBUPROFEN', 7023);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('39992456', 'IBUPROFEN', 'CVS PHARMACY', 'CVS PHARMACY IBUPROFEN', 163);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('50652618', 'MECLIZINE HCL', 'WALGREEN CO.', 'MOTION SICKNESS RELIEF', 9988);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('84072466', 'ISOXSUPRINE HYDROCHLORIDE', 'BI-COASTAL PHARMACEUTICAL CORPORATION', 'ISOXSUPRINE HYDROCHLORIDE', 1754);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('66105203', 'DIPHENHYDRAMINE HCL', 'FAMILY DOLLAR', 'ALLERGY RELIEF', 8838);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('57514108', 'METRONIDAZOLE', 'A-S MEDICATION SOLUTIONS LLC', 'METRONIDAZOLE', 7232);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('14522916', 'AVOBENZONE, OCTISALATE, ZINC OXIDE, OCTINOXATE, AND OXYBENZONE', 'VENTURA CORPORATION LTD', 'CY BETTER LIPS BALM HUMECTANTE PARA LABIOS CON COLOR FPS 18', 9959);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('88713053', 'ALCOHOL', 'GOJO INDUSTRIES, INC.', 'ETHYL ALCOHOL', 9820);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('91489663', 'RABBIT EPITHELIUM', 'NELCO LABORATORIES, INC.', 'RABBIT EPITHELIUM', 4293);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('59588719', 'LEVOBUNOLOL HYDROCHLORIDE', 'BAUSCH & LOMB INCORPORATED', 'LEVOBUNOLOL HYDROCHLORIDE', 5333);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('38985404', 'INDAPAMIDE', 'ACTAVIS ELIZABETH LLC', 'INDAPAMIDE', 1035);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('65481642', 'CALCAREA CARBONICA, CAUSTICUM, CHLORAMPHENICOLUM, COLCHICUM AUTUMNALE, GAMBOGIA, HISTAMINUM HYDROCHLORICUM, HYDRASTIS CANADENSIS, ICHTHYOLUM, LECITHIN, OVA TOSTA, OVI GALLINAE PELLICULA, PULSATILLA, PYROGENIUM', 'KING BIO INC.', 'EGGS AND MEATS INTOLERANCES', 7772);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('61546026', 'LINACLOTIDE', 'FOREST LABORATORIES, INC.', 'LINZESS', 7182);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('59836541', 'SOYBEAN OIL', 'BAXTER HEALTHCARE CORPORATION', 'INTRALIPID', 5726);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('33320853', 'LAMOTRIGINE', 'ZYDUS PHARMACEUTICALS (USA) INC.', 'LAMOTRIGINE', 2000);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('30674244', 'NAFCILLIN SODIUM', 'SANDOZ INC', 'NAFCILLIN SODIUM', 8443);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('43634505', 'ESCITALOPRAM', 'CAMBER PHARMACEUTICALS', 'ESCITALOPRAM', 3754);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('20468244', 'ACETAMINOPHEN AND CODEINE', 'REMEDYREPACK INC.', 'ACETAMINOPHEN AND CODEINE', 2245);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('47448137', 'ALLSCALE', 'ANTIGEN LABORATORIES, INC.', 'ALLSCALE', 9858);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('53275685', 'ANTICOAGULANT CITRATE PHOSPHATE DEXTROSE (CPD) AND AS-5 RED CELL PRESERVATIVE', 'TERUMO CORPORATION', 'TERUFLEX BLOOD BAG SYSTEM ANTICOAGULANT CITRATE PHOSPHATE DEXTROSE (CPD) AND OPTISOL RED CELL PRESERVATIVE', 7662);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('26292149', 'AVOBENZONE AND OCTINOXATE', 'KANEBO COSMETICS INC.', 'SENSAI LIP BASE', 5398);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('31635216', 'TRICHOTHECIUM ROSEUM', 'NELCO LABORATORIES, INC.', 'TRICHOTHECIUM ROSEUM', 3364);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('37854134', 'CANDIDA ALBICANS', 'SANUM KEHLBECK GMBH & CO. KG', 'PLEO SAN CAND', 3898);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('41606309', 'NECTARINE', 'NELCO LABORATORIES, INC.', 'NECTARINE', 3832);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('30129990', 'ALBUMIN (HUMAN)', 'GRIFOLS USA, LLC', 'HUMAN ALBUMIN GRIFOLS', 8616);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('60608357', 'ACETAMINOPHEN', 'CVS PHARMACY', 'INFANTS PAIN AND FEVER', 4963);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('14893216', 'KETOPROFEN', 'MYLAN PHARMACEUTICALS INC.', 'KETOPROFEN', 2682);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('05457087', 'DEXTROSE (GLUCOSE), LEVULOSE (FRUCTOSE), PHOSPHORIC ACID', 'L PERRIGO COMPANY', 'GOOD SENSE ANTI NAUSEA', 351);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('81516050', 'BUTALBITAL AND ACETAMINOPHEN', 'INTERNATIONAL ETHICAL LABS, INC.', 'TENCON', 8057);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('42090948', 'COTTONWOOD, COMMON POPULUS DELTOIDES', 'JUBILANT HOLLISTERSTIER LLC', 'POLLENS - TREES, COTTONWOOD, COMMON POPULUS DELTOIDES', 4686);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('62164236', 'ALUMINUM CHLOROHYDRATE', 'TOM''S OF MAINE, INC.', 'NATURALLY DRY', 561);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('81639609', 'OCTINOXATE', 'AVON PRODUCTS, INC.', 'EXTRALASTING', 2647);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('30460026', 'NAPROXEN', 'AIDAREX PHARMACEUTICALS LLC', 'NAPROXEN', 7181);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('38078458', 'HYDROXYZINE HYDROCHLORIDE', 'PD-RX PHARMACEUTICALS, INC.', 'HYDROXYZINE HYDROCHLORIDE', 1123);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('57263690', 'ATORVASTATIN CALCIUM', 'CARILION MATERIALS MANAGEMENT', 'ATORVASTATIN CALCIUM', 9899);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('17109099', 'IOVERSOL', 'MALLINCKRODT INC.', 'OPTIRAY', 6375);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('68959388', 'IBUPROFEN', 'BRYANT RANCH PREPACK', 'IBUPROFEN', 6366);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('94940840', 'DOCUSATE SODIUM', 'WALGREENS', 'STOOL SOFTENER', 8782);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('20078241', 'RISPERIDONE', 'CONTRACT PHARMACY SERVICES-PA', 'RISPERIDONE', 2608);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('84888830', 'BRYONIA ALBA ROOT, SEPIA', 'ALVA-AMCO PHARMACAL COMPANIES, INC.', 'NAUZENE', 4909);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('27624854', 'GLYCERIN, DIMETHICONE', 'NATURE REPUBLIC CO., LTD.', 'HAND AND NATURE ANTI WRINKLE HAND', 4624);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('99867928', 'CEFIXIME', 'LUPIN PHARMA', 'SUPRAX', 9907);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('28003310', 'ARNICA MONTANA, BELLIS PERENNIS, HYPERICUM PERFORATUM, LEDUM PALUSTRE TWIG, AND RUTA GRAVEOLENS FLOWERING TOP', 'HYLAND''S', 'MUSCLE THERAPY WITH ARNICA', 6436);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('80038037', 'ALENDRONATE SODIUM', 'REMEDYREPACK INC.', 'ALENDRONATE SODIUM', 6109);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('38697854', 'IBUPROFEN', 'STAT RX USA LLC', 'IBUPROFEN', 2020);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('15870316', 'BACITRACIN ZINC, NEOMYCIN SULFATE, AND POLYMYXIN B SULFATE', 'NASH-FINCH COMPANY', 'OUR FAMILY', 2061);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('98989341', 'AMINOHIPPURATE SODIUM', 'MERCK SHARP & DOHME CORP.', 'AMINOHIPPURATE SODIUM', 2032);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('90665406', 'AVOBENZONE, OCTISALATE, OCTOCRYLENE', 'PRIME PACKAGING, INC.', 'AUSTRALIAN GOLD', 3978);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('15968658', 'NITROGLYCERIN', 'PARKE-DAVIS DIV OF PFIZER INC', 'NITROSTAT', 7298);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('30662514', 'HYDROCHLOROTHIAZIDE', 'APHENA PHARMA SOLUTIONS - TENNESSEE, LLC', 'HYDROCHLOROTHIAZIDE', 3145);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('50458736', 'BETAMETHASONE DIPROPIONATE', 'PERRIGO NEW YORK INC', 'BETAMETHASONE DIPROPIONATE', 3966);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('84725088', 'MEPERIDINE HYDROCHLORIDE', 'WEST-WARD PHARMACEUTICAL CORP.', 'MEPERIDINE HYDROCHLORIDE', 3864);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('07119504', 'CITALOPRAM', 'CAMBER PHARMACEUTICALS', 'CITALOPRAM', 9574);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('12619041', 'CISATRACURIUM BESYLATE', 'SAGENT PHARMACEUTICALS', 'CISATRACURIUM BESYLATE', 4119);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('75184610', 'SALINE LAXATIVE', 'WESTERN FAMILY HOLDING COMPANY', 'WESTERN FAMILY', 1988);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('39710256', 'IBUPROFEN', 'TOP CARE (TOPCO ASSOCIATES LLC)', 'IBUPROFEN', 9452);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('09337632', 'CLADOSPORIUM HERBARUM', 'ANTIGEN LABORATORIES, INC.', 'CLADOSPORIUM HERBARUM', 2776);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('42596724', 'LABETALOL HYDROCHLORIDE', 'GLAND PHARMA LIMITED', 'LABETALOL HYDROCHLORIDE', 3210);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('44752260', 'PHYTONADIONE', 'REBEL DISTRIBUTORS CORP', 'MEPHYTON', 5874);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('76644916', 'AMITRIPTYLINE HYDROCHLORIDE', 'PD-RX PHARMACEUTICALS, INC.', 'AMITRIPTYLINE HYDROCHLORIDE', 1970);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('24477959', 'ASPIRIN', 'WALGREEN CO.', 'LOW DOSE ASPIRIN', 9681);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('08201157', 'OCTINOXATE, TITANIUM DIOXIDE', 'PARFUMS CHRISTIAN DIOR', 'CD DIORSNOW WHITE REVEAL UV SHIELD FOUNDATION 021-LINEN', 2614);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('88949106', 'TITANIUM DIOXIDE', 'SHISEIDO AMERICA INC.', 'SHISEIDO SUN PROTECTION FOUNDATION', 4848);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('42965300', 'TITANIUM DIOXIDE', 'L''OREAL USA PRODUCTS INC', 'LOREAL PARIS VISIBLE LIFT REPAIR ABSOLUTE RAPID AGE REVERSING MAKEUP BROAD SPECTRUM SPF 16 SUNSCREEN', 1132);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('04291894', 'DEXTROMETHORPHAN HYDROBROMIDE AND PHENYLEPHRINE HYDROCHLORIDE', 'BIO-PHARM, INC.', 'ASSURED DAY TIME COLD AND COUGH', 6786);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('33397263', 'BENZALKONIUM CHLORIDE', 'CVS PHARMACY', 'CVS', 7902);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('85638953', 'FLUDARABINE PHOSPHATE', 'APP PHARMACEUTICALS, LLC', 'FLUDARABINE', 4832);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('17673009', 'SODIUM FLUORIDE', 'DENTOVATIONS INC', 'POWER WHITE', 1384);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('99011154', 'NORELGESTROMIN AND ETHINYL ESTRADIOL', 'MYLAN PHARMACEUTICALS INC.', 'XULANE', 7060);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('81445612', 'RIVASTIGMINE TARTRATE', 'MACLEODS PHARMACEUTICALS LIMITED', 'RIVASTIGMINE TARTRATE', 2212);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('38898670', 'ESCITALOPRAM', 'NORTHWIND PHARMACEUTICALS', 'ESCITALOPRAM', 1648);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('44298337', 'GENTIAN VIOLET 1%', 'HUMCO HOLDING GROUP, INC.', 'HUMCO GENTIAN VIOLET 1%', 6655);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('66369016', 'DEXAMETHASONE', 'PD-RX PHARMACEUTICALS, INC.', 'DEXAMETHASONE', 3668);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('47982100', 'ALDER WHITE', 'ALK-ABELLO, INC.', 'ALNUS INCANA SSP RUGOSA POLLEN', 7689);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('07923700', 'AVOBENZONE, OCTINOXATE, OCTISALATE, AND OCTOCRYLENE', 'GUTHY-RENKER LLC', 'PRINCIPAL SECRET', 9929);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('61495713', 'HYDROCODONE BITARTRATE AND ACETAMINOPHEN', 'STAT RX USA LLC', 'HYDROCODONE BITARTRATE AND ACETAMINOPHEN', 6924);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('18146023', 'FLUPHENAZINE HYDROCHLORIDE', 'SANDOZ INC', 'FLUPHENAZINE HYDROCHLORIDE', 2870);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('57266001', 'ACONITUM NAPELLUS, ARSENICUM ALBUM, AVENA SATIVA, BELLADONNA, CAMPHORA, CINCHONA OFFICINALIS, COFFEA CRUDA, CYPRIPEDIUM PUBESCENS, HYOSCYAMUS NIGER, IGNATIA AMARA, PASSIFLORA INCARNATA, PULSATILLA, VALERIANA OFFICINALIS,AESCULUS HIPPOCASTANUM, FLOS', 'KING BIO INC.', 'SLEEP AID', 4664);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('51519825', 'ZALEPLON', 'BRYANT RANCH PREPACK', 'ZALEPLON', 9895);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('03860434', 'POTASSIUM CHLORIDE', 'REMEDYREPACK INC.', 'POTASSIUM CHLORIDE', 5110);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('09356975', 'PIROXICAM, .GAMMA.-AMINOBUTYRIC ACID', 'PHYSICIAN THERAPEUTICS LLC', 'THERAFELDAMINE', 1736);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('01059572', 'RIVASTIGMINE TARTRATE', 'NOVARTIS PHARMACEUTICALS CORPORATION', 'EXELON', 8256);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('28921649', 'CYCLOSPORINE', 'CARDINAL HEALTH', 'CYCLOSPORINE', 6641);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('94405900', 'OCTINOXATE', 'BEIERSDORF INC', 'NIVEA FOR MEN SENSITIVE', 9727);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('00213893', 'PANCRELIPASE', 'APTALIS PHARMA US, INC.', 'ZENPEP', 1957);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('53232525', 'ANTICARIES', 'ORAL BIOTECH', 'CTX3 RINSE', 8926);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('51045569', 'MAGNESIUM HYDROXIDE', 'MAJOR PHARMACEUTICALS INC.', 'MILK OF MAGNESIA MINT', 1239);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('99208453', 'BENZALKONIUM CHLORIDE', 'FAMILY HOSPITALITY LLC', 'BZK CLEANSING', 4929);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('59783315', 'CARVEDILOL', 'CARDINAL HEALTH', 'CARVEDILOL', 9341);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('18397371', 'BAY LEAF', 'NELCO LABORATORIES, INC.', 'BAY LEAF', 6796);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('21979695', 'TOLNAFTATE', 'EFFICIENT LABORATORIES INC', 'HONGO KILLER', 8444);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('25358963', 'SODIUM FLUORIDE AND POTASSIUM NITRATE', 'COLGATE ORAL PHARMACEUTICALS, INC.', 'PREVIDENT 5000 ENAMEL PROTECT', 2926);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('62915361', 'FLUOXETINE HCL', 'EDGEMONT PHARMACEUTICALS, LLC', 'FLUOXETINE HCL', 8061);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('96660045', 'PLANTAIN ENGLISH', 'ALK-ABELLO, INC.', 'PLANTAGO LANCEOLATA POLLEN', 996);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('12135744', 'TREATMENT SET TS338910', 'ANTIGEN LABORATORIES, INC.', 'TREATMENT SET TS338910', 2480);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('13343487', 'BACITRACIN ZINC', 'FARIA LLC DBA SHEFFIELD PHARMACEUTICALS', 'SHEFFIELD BACITRACIN ZINC', 3793);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('58815945', 'SALMON', 'ALK-ABELLO, INC.', 'SALMON', 3449);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('65603407', 'RANITIDINE', 'CLINICAL SOLUTIONS WHOLESALE', 'RANITIDINE', 1073);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('53585544', 'LITHIUM CARBONATE', 'ROXANE LABORATORIES, INC', 'LITHIUM CARBONATE', 1338);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('69455958', 'FUCUS VESICULOSUS', 'HOMEOLAB USA INC.', 'FUCUS VESICULOSUS', 867);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('09554687', 'HYDROCODONE BITARTRATE AND ACETAMINOPHEN', 'APHENA PHARMA SOLUTIONS - TENNESSEE, INC.', 'HYDROCODONE BITARTRATE AND ACETAMINOPHEN', 6228);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('24488194', 'TITANIUM DIOXIDE', 'CLINIQUE LABORATORIES INC', 'CX DAILY EYE PROTECTOR', 9275);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('32285600', 'NORTRIPTYLINE HYDROCHLORIDE', 'REMEDYREPACK INC.', 'NORTRIPTYLINE HYDROCHLORIDE', 3617);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('77444389', 'OCTINOXATE, OCTISALATE, OXYBENZONE, AND TITANIUM DIOXIDE', 'SMASHBOX BEAUTY COSMETICS, INC', 'CAMERA READY', 3583);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('01468307', 'GABAPENTIN', 'GOLDEN STATE MEDICAL SUPPLY, INC.', 'GABAPENTIN', 2796);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('05828667', 'SODIUM FLUORIDE', 'HEB', 'ANTICAVITY FLUORIDE RINSE', 3270);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('51994577', 'FEXOFENADINE HCL', 'MCKESSON', 'HEALTH MART FEXOFENADINE HYDROCHLORIDE', 1448);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('80513474', 'IODINATED I-131 ALBUMIN', 'ISO-TEX DIAGNOSTICS, INC.', 'VOLUMEX', 6332);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('58546608', 'WATER OAK', 'NELCO LABORATORIES, INC.', 'WATER OAK', 9784);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('11242781', 'FAMOTIDINE', 'DIRECT RX', 'FAMOTIDINE', 8958);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('78023649', 'CLOBETASOL PROPIONATE', 'TARO PHARMACEUTICALS U.S.A., INC.', 'CLOBETASOL PROPIONATE', 3406);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('83399143', 'FLUVOXAMINE MALEATE', 'ANIP ACQUISITION COMPANY', 'FLUVOXAMINE MALEATE', 7711);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('12099821', 'GUAIFENESIN, PHENYLEPHRINE HCL', 'WALGREEN CO.', 'WAL-PHED PE NON-DRYING SINUS', 2797);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('00813163', 'PROMETHAZINE HYDROCHLORIDE', 'TEVA PARENTERAL MEDICINES, INC.', 'PROMETHAZINE HYDROCHLORIDE', 1942);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('87393796', 'OCTINOXATE, OXYBENZONE, AND PETROLATUM', 'BLISTEX INC.', 'BLISTEX', 4179);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('03689161', 'CETIRIZINE HYDROCHLORIDE', 'PUBLIX SUPER MARKETS INC', 'CHILDRENS ALLERGY', 9073);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('83809397', 'ACETAMINOPHEN', 'AMERICAN SALES COMPANY', 'CARE ONE PAIN RELIEF', 7565);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('18487497', 'POLYETHYLENE GLYCOL 3350', 'VALLEY MEDICAL PRODUCTS,LLC', 'EZ2GO', 7998);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('65040402', 'FLUOCINOLONE ACETONIDE', 'AMNEAL PHARMACEUTICALS, LLC', 'FLUOCINOLONE ACETONIDE', 9719);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('08813510', 'VASOPRESSIN', 'AMERICAN REGENT, INC.', 'VASOPRESSIN', 6497);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('64121708', 'SALICYLIC ACID', 'DERMALOGICA, INC.', 'CLEARING MATTIFIER', 6561);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('15697128', 'RISPERIDONE', 'STATE OF FLORIDA DOH CENTRAL PHARMACY', 'RISPERIDONE', 3931);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('45764410', 'ACETAMINOPHEN, CHLORPHENIRAMINE MALEATE, PHENYLEPHRINE HCL', 'PFIZER CONSUMER HEALTHCARE', 'DRISTAN COLD MULTISYMPTOM', 3597);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('07111884', 'METFORMIN HYDROCHLORIDE', 'CARDINAL HEALTH', 'METFORMIN HYDROCHLORIDE', 1275);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('04655735', 'DICYCLOMINE HYDROCHLORIDE', 'CLINICAL SOLUTIONS WHOLESALE', 'DICYCLOMINE HYDROCHLORIDE', 8553);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('93549856', 'METFORMIN HYDROCHLORIDE', 'WATSON LABORATORIES, INC.', 'METFORMIN HYDROCHLORIDE', 9583);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('77521263', 'METOPROLOL SUCCINATE', 'ASTRAZENECA LP', 'TOPROL', 3995);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('88213532', 'BENZONATATE', 'KAISER FOUNDATION HOSPITALS', 'BENZONATATE', 4183);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('90446699', 'GUANFACINE HYDROCHLORIDE', 'AMNEAL PHARMACEUTICALS', 'GUANFACINE HYDROCHLORIDE', 9779);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('47505736', 'EPINEPHRINE', 'PHYSICIANS TOTAL CARE, INC.', 'EPIPEN', 3902);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('57819363', 'ACETAMINOPHEN, DIPHENHYDRAMINE HCL', 'CHAIN DRUG CONSORTIUM, LLC (PREMIER VALUE)', 'NON ASPIRIN PM', 8754);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('30628331', 'DICLOFENAC SODIUM', 'MEDSOURCE PHARMACEUTICALS', 'DICLOFENAC SODIUM', 2133);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('45906393', 'FLUORIDE TREATMENT', 'ROSS HEALTHCARE INC.', 'PCXX NEUTRAL GEL VANILLA ORANGE', 6667);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('82316405', 'CALCIUM CARBONATE', 'MIDWAY IMPORTING', 'CALCID', 7613);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('98414034', 'DOXYCYCLINE HYCLATE', 'CONTRACT PHARMACY SERVICES-PA', 'DOXYCYCLINE HYCLATE', 9651);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('78825461', 'HOUSE DUST', 'ALK-ABELLO, INC.', 'HOUSE DUST', 3386);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('17743154', 'TERCONAZOLE', 'PHYSICIANS TOTAL CARE, INC.', 'TERCONAZOLE', 711);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('38933355', 'MEPROBAMATE', 'ALEMBIC PHARMACEUTICALS LIMITED', 'MEPROBAMATE', 547);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('20390694', 'DIPHENHYDRAMINE HYDROCHLORIDE', 'P AND L DEVELOPMENT OF NEW YORK COMPANY', 'ANTIHISTIMINE ALLERGY', 8995);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('87518589', 'ALUMINUM HYDROXIDE, MAGNESIUM HYDROXIDE, SIMETHICONE', 'WESTERN FAMILY FOODS INC', 'ANTACID', 4872);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('44586309', 'SENNOSIDES A AND B', 'CARILION MATERIALS MANAGEMENT', 'SENNA', 4672);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('96775755', 'OLANZAPINE', 'DISPENSING SOLUTIONS, INC.', 'OLANZAPINE', 8034);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('29976024', 'BENZOCAINE', 'SAFCO DENTAL SUPPLY CO.', 'TOPICAL ANESTHETIC', 2497);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('32486670', 'LEUPROLIDE ACETATE', 'ABBVIE INC.', 'LUPRON DEPOT-PED', 6240);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('21783144', 'ETHYL ALCOHOL', 'ADVANCED BEAUTY SYSTEMS, INC.', 'TOASTED VANILLA SUGAR HAND SANITIZER', 5383);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('50681346', 'EUCALYPTOL, MENTHOL, METHYL SALICYLATE, THYMOL', 'HYVEE INC', 'HYVEE', 7681);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('35486144', 'PYRITHIONE ZINC', 'DAVINES S.P.A.', 'NATURALTECH PURIFYING ANTI-DANDRUFF', 7819);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('94825436', 'SENNOSIDES', 'L.N.K. INTERNATIONAL, INC.', 'MAXIMUM STRENGTH LAXATIVE', 1535);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('38057704', 'GABAPENTIN', 'GOLDEN STATE MEDICAL SUPPLY, INC.', 'GABAPENTIN', 3762);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('80366449', 'BENZALKONIUM CHLORIDE', 'WAYNE CONCEPT MANUFACTURING CO INC', 'BAC STOP', 6664);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('34846010', 'NAPROXEN SODIUM', 'TOPCO ASSOCIATES LLC', 'TOPCARE ALL DAY PAIN RELIEF', 3803);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('88408226', 'DIMENHYDRINATE', 'MEDTECH PRODUCTS INC.', 'DRAMAMINE ORANGE', 9977);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('35732799', 'VALACYCLOVIR HYDROCHLORIDE', 'LIFE LINE HOME CARE SERVICES, INC.', 'VALACYCLOVIR HYDROCHLORIDE', 4799);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('23209645', 'DEXTROMETHORPHAN HBR, GUAIFENESIN AND PSEUDOEPHEDRINE HCL', 'POLY PHARMACEUTICALS, INC.', 'POLY-VENT DM', 7741);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('51938693', 'ACETAMINOPHEN', 'SUPERVALU INC.', 'EXTRA STRENGTH PAIN RELIEF', 7959);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('73134200', 'NAPROXEN SODIUM', 'DZA BRANDS LLC', 'HEALTHY ACCENTS NAPROXEN SODIUM', 3917);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('39911892', 'ASTERIAS RUBENS, AUR. MET., BELLADONNA, BENZOICUM ACIDUM, BERBER. VULG., BRYONIA, CALC. CARB., CANTHARIS, CEANOTHUS, CHELIDONIUM MAJUS, CHIONANTHUS VIRGINICA, CINCHONA, DIOSCOREA, IRIS VERSICOLOR, NAT. CARB., NUX VOM., PTELEA, CARDUUS MAR., ECHINACEA, SOLIDAGO, TARAXACUM', 'NEWTON LABORATORIES, INC.', 'LYMPH ASSIST', 293);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('52641489', 'BROMPHENIRAMINE MALEATE, DEXTROMETHORPHAN HYDROBROMIDE AND PHENYLEPHRINE HYDROCHLORIDE', 'ACCUDIAL PHARMACEUTICAL, INC.', 'RUNNY NOSE AND COUGH', 6693);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('90334529', 'DIVALPROEX SODIUM', 'SUN PHARMACEUTICAL INDUSTRIES LIMITED', 'DIVALPROEX SODIUM', 7125);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('38494583', 'TOPOTECAN HYDROCHLORIDE', 'GLAXOSMITHKLINE LLC', 'HYCAMTIN', 3296);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('37219108', 'SODIUM CHLORIDE', 'HOSPIRA, INC.', 'SODIUM CHLORIDE', 6989);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('51347026', 'GLYCERIN', 'NATURE REPUBLIC CO., LTD.', 'MACCOLA', 7188);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('95237036', 'ABROTANUM (ARTEMISIA ABROTANUM), ANACARDIUM ORIENTALE, BARYTA MURIATICA, CALCAREA CARBONICA, CALCAREA PHOSPHORICA, FUCUS VESICULOSUS, GRAPHITES, HELLEBORUS NIGER,', 'ARIZE SUPPLEMENTS, LLC', 'MAX', 8046);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('61385379', 'HYDROCORTISONE', 'THE KROGER COMPANY', 'HYDROCORTISONE MAXIMUM STRENGTH PLUS 12 MOISTURIZERS', 9607);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('44121070', 'NEOMYCIN SULFATE', 'UNITED EXCHANGE CORP.', 'FAMILY CARE TRIPLE ANTIBIOTIC PAIN RELIEF', 2214);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('44895795', 'NICOTINE POLACRILEX', 'MCKESSON', 'SUNMARK NICOTINE', 6174);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('76058157', 'DIPHENHYDRAMINE HYDROCHLORIDE, ZINC ACETATE', 'MAJOR PHARMACEUTICALS', 'BANOPHEN', 7543);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('48051885', 'POPLAR MIXTURE', 'ANTIGEN LABORATORIES, INC.', 'POPLAR MIXTURE', 8130);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('66556610', 'ACETAMINOPHEN, CHLORPHENIRAMINE MALEATE, AND PHENYLEPHRINE HYDROCHLORIDE', 'BAYER CORPORATION CONSUMER CARE DIVISION', 'ALKA-SELTZER PLUS FAST PACKS COLD AND FLU FORMULA', 7364);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('35041753', 'MINOXIDIL', 'PAR PHARMACEUTICAL INC', 'MINOXIDIL', 4791);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('18422028', 'SWEETGUM', 'ALK-ABELLO, INC.', 'LIQUIDAMBAR STYRACIFLUA POLLEN', 3674);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('98284647', 'OCTINOXATE, OCTISALATE, TITANIUM DIOXIDE', 'BENEFIT COSMETICS, LLC', 'BENEFIT BIG EASY BROAD SPECTRUM SPF 35 SUNSCREEN MULTI-BALANCING COMPLEXION PERFECTOR - 04 MEDIUM', 1051);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('73453321', 'HYDROCHLOROTHIAZIDE', 'DAVA PHARMACEUTICALS, INC.', 'HYDROCHLOROTHIAZIDE', 4068);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('43747984', 'FUSARIUM VASINFECTUM', 'ALK-ABELLO, INC.', 'FUSARIUM OXYSPORUM VASINFECTUM', 2067);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('42536276', 'TRIMETHOPRIM', 'NOVEL LABORATORIES,INC.', 'TRIMETHOPRIM', 9833);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('40674860', 'HUMAN IMMUNOGLOBULIN G', 'BAXTER HEALTHCARE CORPORATION', 'GAMMAGARD', 6440);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('92021829', 'MANDRAGORA ARNICA SPECIAL ORDER', 'URIEL PHARMACY INC.', 'MANDRAGORA ARNICA SPECIAL ORDER', 9624);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('99867838', 'PYRITHIONE ZINC', 'SAFEWAY INC.', 'SAFEWAY', 4849);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('10434678', 'ETHYL ALCOHOL', 'AMERICAN SALES COMPANY', 'CARE ONE', 512);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('86918890', 'HYDROCORTISONE', 'PADDOCK LABORATORIES, INC.', 'HYDROCORTISONE', 5898);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('44715715', 'NITROGLYCERIN', 'MERCK SHARP & DOHME CORP.', 'NITRO-DUR', 1127);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('70872839', 'MENTHOL', 'PURE SCIENCE INTERNATIONAL, INC.', 'ARTHRI-SUPPORT', 121);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('60604084', 'CAPSAICIN AND MENTHOL', 'HEALTH CARE PRODUCTS', 'ZOSTRIX DIABETIC JOINT AND ARTHRITIS PAIN RELIEF', 6289);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('50359633', 'PREDNISONE', 'QUALITEST PHARMACEUTICALS', 'PREDNISONE', 5968);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('87287836', 'MINERAL OIL, PETROLATUM, PHENYLEPHRINE HCL', 'RITE AID CORPORATION', 'HEMORRHOIDAL RELIEF', 3709);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('00374676', 'AIR', 'OXARC, INC.', 'AIR', 961);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('44113535', 'NIFEDIPINE', 'LAKE ERIE MEDICAL DBA QUALITY CARE PRODUCTS LLC', 'NIFEDIPINE', 975);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('60894158', 'PENTOXIFYLLINE', 'STATE OF FLORIDA DOH CENTRAL PHARMACY', 'PENTOXIFYLLINE', 1815);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('83379095', 'OXICONAZOLE NITRATE', 'PHARMADERM, A DIVISION OF NYCOMED US INC.', 'OXISTAT', 1448);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('71184760', 'LEVETIRACETAM', 'PD-RX PHARMACEUTICALS, INC.', 'LEVETIRACETAM', 9860);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('91058405', 'OXYGEN', 'OXYGEN PLUS', 'OXYGEN', 7701);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('96643511', 'BENZOYL PEROXIDE', 'TAGI PHARMA INC.', 'BENZOYL PEROXIDE EMOLLIENT', 160);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('60573241', 'ROPINIROLE HYDROCHLORIDE', 'ZHEJIANG HUAHAI PHARMACEUTICAL CO., LTD.', 'ROPINIROLE HYDROCHLORIDE', 8529);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('67032371', 'ENOXAPARIN SODIUM', 'SANOFI-AVENTIS U.S. LLC', 'LOVENOX', 7653);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('73046908', 'TRAMADOL HYDROCHLORIDE, GABA', 'PHYSICIAN THERAPEUTICS LLC', 'THERATRAMADOL-60', 2680);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('43907655', 'LOSARTAN POTASSIUM', 'GOLDEN STATE MEDICAL SUPPLY, INC.', 'LOSARTAN POTASSIUM', 3043);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('09503369', 'TRICLOSAN', 'H.E.B.', 'ORCHID', 4663);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('67363291', 'AVOBENZONE,HOMOSALATE, OCTISALATE,OCTOCRYLENE,OXYBENZONE', 'OLE HENRIKSEN OF DENMARK', 'PROTECT THE TRUTH SPF 50', 787);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('73659355', 'GUAIFENESIN', 'DZA BRANDS LLC', 'HEALTHY ACCENTS CHILDRENS MUCUS RELIEF', 7357);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('37426414', 'OLANZAPINE', 'MYLAN PHARMACEUTICALS INC.', 'OLANZAPINE', 8879);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('71874576', 'TOLNAFTATE', 'PEDICIS RESEARCH LLC', 'CIDACIN ANTIFUNGAL TREATMENT', 8666);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('69460728', 'SODIUM ASCORBATE, CHOLECALCIFEROL, .ALPHA.-TOCOPHEROL ACETATE, D-, THIAMINE MONONITRATE, RIBOFLAVIN, NIACINAMIDE, PYRIDOXINE HYDROCHLORIDE, FOLIC ACID, CYANOCOBALAMIN, CALCIUM FORMATE, CALCIUM CARBONATE, FERROUS BISGLYCINATE, POTASSIUM IODIDE, ZINC OXIDE, CHOLINE BITARTRATE', 'WH NUTRITIONALS, LLC', 'NUTRI-TAB OB', 480);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('70701108', 'MULTI-VITAMIN WITH FLUORIDE', 'LIBERTAS PHARMA, INC.', 'MULTI-VITAMIN WITH FLUORIDE', 1118);
insert into drug (drug_id, drug_name, manufacturer, commercial_name, price) values ('89036292', 'ASCORBIC ACID, CHOLECALCIFEROL, .ALPHA.-TOCOPHEROL, DL-, PYRIDOXINE HYDROCHLORIDE, FOLIC ACID, CYANOCOBALAMIN, CALCIUM CARBONATE, FERROUS FUMARATE, MAGNESIUM OXIDE AND DOCONEXENT', 'AVION PHARMACEUTICALS, LLC', 'PRENATE DHA', 7584);
