insert into store (store_id, store_location, employees) values ('847', 'Tennessee', 11);
insert into store (store_id, store_location, employees) values ('504', 'Minnesota', 10);
insert into store (store_id, store_location, employees) values ('843', 'California', 5);
insert into store (store_id, store_location, employees) values ('999', 'Tennessee', 27);
insert into store (store_id, store_location, employees) values ('712', 'Utah', 20);
insert into store (store_id, store_location, employees) values ('087', 'Illinois', 12);
insert into store (store_id, store_location, employees) values ('933', 'Hawaii', 22);
insert into store (store_id, store_location, employees) values ('227', 'Ohio', 30);
insert into store (store_id, store_location, employees) values ('927', 'Tennessee', 11);
insert into store (store_id, store_location, employees) values ('140', 'Ohio', 16);
insert into store (store_id, store_location, employees) values ('538', 'Florida', 28);
insert into store (store_id, store_location, employees) values ('875', 'Washington', 8);
insert into store (store_id, store_location, employees) values ('832', 'New York', 7);
insert into store (store_id, store_location, employees) values ('486', 'Virginia', 5);
insert into store (store_id, store_location, employees) values ('080', 'New York', 29);
insert into store (store_id, store_location, employees) values ('168', 'Texas', 22);
insert into store (store_id, store_location, employees) values ('408', 'Ohio', 17);
insert into store (store_id, store_location, employees) values ('951', 'Ohio', 13);
insert into store (store_id, store_location, employees) values ('147', 'New York', 23);
insert into store (store_id, store_location, employees) values ('439', 'Virginia', 6);
insert into store (store_id, store_location, employees) values ('718', 'California', 30);
insert into store (store_id, store_location, employees) values ('717', 'Texas', 26);
insert into store (store_id, store_location, employees) values ('771', 'North Carolina', 11);
insert into store (store_id, store_location, employees) values ('161', 'New York', 16);
insert into store (store_id, store_location, employees) values ('379', 'Florida', 6);
insert into store (store_id, store_location, employees) values ('886', 'Florida', 25);
